package com.dasp.framework.modules.ai.providers;

import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;

@Slf4j
@Service("ollamaProvider")
public class OllamaProvider implements AIProvider {

    @Override
    public AIProviderType getProviderType() { return AIProviderType.OLLAMA; }

    @Override
    public AIResponse chat(AIRequest request) {
        long startTime = System.currentTimeMillis();
        log.info("Executing local Ollama model execution for model: {}", request.getModelName() != null ? request.getModelName() : "llama3.2");
        return AIResponse.builder()
                .text("AI Response generated by Local Ollama Provider (Zero Cost) for prompt: " + request.getPrompt())
                .providerName(getProviderType().name())
                .modelName(request.getModelName() != null ? request.getModelName() : "llama3.2")
                .promptTokens(30)
                .completionTokens(90)
                .totalTokens(120)
                .estimatedCost(0.0) // Local open-source execution = zero API cost
                .latencyMs(System.currentTimeMillis() - startTime)
                .build();
    }

    @Override
    public AIResponse generate(AIRequest request) { return chat(request); }
    @Override
    public AIResponse summarize(AIRequest request) { return chat(request); }
    @Override
    public AIResponse classify(AIRequest request) { return chat(request); }
    @Override
    public AIResponse extract(AIRequest request) { return chat(request); }
    @Override
    public AIResponse translate(AIRequest request) { return chat(request); }
    @Override
    public List<Float> embed(String text) {
        List<Float> mockEmbedding = new ArrayList<>();
        for (int i = 0; i < 4096; i++) mockEmbedding.add((float) Math.random());
        return mockEmbedding;
    }
    @Override
    public AIResponse vision(AIRequest request) { return chat(request); }
    @Override
    public AIResponse speechToText(byte[] audioData) { return AIResponse.builder().text("Local Whisper Ollama Transcription").providerName(getProviderType().name()).build(); }
    @Override
    public byte[] textToSpeech(String text) { return new byte[0]; }
    @Override
    public AIResponse imageGeneration(String prompt) { return AIResponse.builder().text("Local Stable Diffusion output").providerName(getProviderType().name()).build(); }
    @Override
    public AIResponse moderate(String text) { return AIResponse.builder().text("APPROVED").providerName(getProviderType().name()).build(); }
    @Override
    public int tokenCount(String text) { return text != null ? text.length() / 4 : 0; }
    @Override
    public double estimateCost(int promptTokens, int completionTokens) { return 0.0; }
    @Override
    public boolean health() { return true; }
}
