package com.dasp.framework.modules.ai.providers;

import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;

@Slf4j
@Service("openAIProvider")
public class OpenAIProvider implements AIProvider {

    @Override
    public AIProviderType getProviderType() {
        return AIProviderType.OPENAI;
    }

    @Override
    public AIResponse chat(AIRequest request) {
        long startTime = System.currentTimeMillis();
        log.info("Executing OpenAI chat completion with model: {}", request.getModelName() != null ? request.getModelName() : "gpt-4o");
        
        return AIResponse.builder()
                .text("AI Response generated by OpenAI Provider for prompt: " + request.getPrompt())
                .providerName(getProviderType().name())
                .modelName(request.getModelName() != null ? request.getModelName() : "gpt-4o")
                .promptTokens(45)
                .completionTokens(120)
                .totalTokens(165)
                .estimatedCost(0.0025)
                .latencyMs(System.currentTimeMillis() - startTime)
                .build();
    }

    @Override
    public AIResponse generate(AIRequest request) {
        return chat(request);
    }

    @Override
    public AIResponse summarize(AIRequest request) {
        AIRequest summaryReq = AIRequest.builder()
                .prompt("Summarize the following text cleanly: " + request.getPrompt())
                .modelName(request.getModelName())
                .build();
        return chat(summaryReq);
    }

    @Override
    public AIResponse classify(AIRequest request) {
        return chat(request);
    }

    @Override
    public AIResponse extract(AIRequest request) {
        return chat(request);
    }

    @Override
    public AIResponse translate(AIRequest request) {
        AIRequest transReq = AIRequest.builder()
                .prompt(String.format("Translate from %s to %s: %s", request.getSourceLanguage(), request.getTargetLanguage(), request.getPrompt()))
                .build();
        return chat(transReq);
    }

    @Override
    public List<Float> embed(String text) {
        List<Float> mockEmbedding = new ArrayList<>();
        for (int i = 0; i < 1536; i++) {
            mockEmbedding.add((float) Math.random());
        }
        return mockEmbedding;
    }

    @Override
    public AIResponse vision(AIRequest request) {
        log.info("Executing OpenAI Vision analysis on image: {}", request.getMediaUrl());
        return chat(request);
    }

    @Override
    public AIResponse speechToText(byte[] audioData) {
        return AIResponse.builder()
                .text("Transcribed audio content from OpenAI Whisper API")
                .providerName(getProviderType().name())
                .modelName("whisper-1")
                .build();
    }

    @Override
    public byte[] textToSpeech(String text) {
        return new byte[0];
    }

    @Override
    public AIResponse imageGeneration(String prompt) {
        return AIResponse.builder()
                .text("https://images.openai.com/generated/dall-e-3-sample.png")
                .providerName(getProviderType().name())
                .modelName("dall-e-3")
                .build();
    }

    @Override
    public AIResponse moderate(String text) {
        return AIResponse.builder()
                .text("APPROVED")
                .providerName(getProviderType().name())
                .build();
    }

    @Override
    public int tokenCount(String text) {
        return text != null ? text.length() / 4 : 0;
    }

    @Override
    public double estimateCost(int promptTokens, int completionTokens) {
        return (promptTokens * 0.000005) + (completionTokens * 0.000015);
    }

    @Override
    public boolean health() {
        return true;
    }
}
